#! /usr/bin/env ruby

# check for # of arguments
if ARGV.length != 1
    puts 'Invalid arguments'
    exit
end

# if the file exists, add numbers(>=2) until you get a new name
file_name = "#{ARGV[0].chomp('.rb')}.rb"
if File.file?(file_name)
    num = 1
    loop do
        num += 1
        file_name = ARGV[0] + num.to_s + '.rb'
        break if !File.file?(file_name)
    end
    puts "File exists. Naming it #{file_name}"
end

# create file, write shebang and newline twice
file = File.new(file_name,'w') 
file.puts('#! /usr/bin/env ruby')
file.puts("\n\n")
file.chmod(0755)
file.close

